# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Brejas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  def all_pods
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireImage'
  end

  # Pods for Brejas

  target 'BrejasTests' do
    # Pods for testing
    all_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'BrejasUITests' do
    # Pods for testing
  end

end
