# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

  def all_pods
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireImage'
    pod 'UIScrollView-InfiniteScroll'
  end

  target 'Brejas' do
    all_pods
  end

  target 'BrejasTests' do
    all_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'BrejasUITests' do
    all_pods
  end
